export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_LIST = 'SET_PLAYING_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_PLAYING_MODE = 'SET_PLAYING_MODE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_DURATION = 'SET_DURATION'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
